# Generated by Django 4.2.21 on 2025-06-18 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_pets_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
