# Generated by Django 4.2.21 on 2025-06-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pets_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='likes',
        ),
    ]
