# Generated by Django 4.2.21 on 2025-07-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_comment_photo'),
        ('accounts', '0006_alter_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
    ]
